### ISSUE TITLE
Fix column's headers

### ISSUE THREAD

**Issue by Bravewarrior0** [thabetx/boarda-release#9]
Is there away to fix the column title while scrolling down?

also there is a problem when we have multiple cards in the same column that it requires scrolling to select cards, the column header is pushed down when we select it.
_note: the problem doesn't happen if we have multiple boards_ 

A photo to explain the problem
![image](https://github.com/thabetx/boarda-release/assets/36136822/b90afc39-8b2a-4d79-8a4d-a0118770fdf6)

**Comment by thabetx** [comment]
The column name going out of the screen is intentional. It's a replacement for the scroll bar as the scroll bar is implemented. So it's an indication that there is some scrolling.

I will take a look at the weird scrolling in the picture above, thanks for noting that it only happens when there is a single board.

**Comment by thabetx** [comment]
The unnecessary scrolling is now fixed and will be available on next release.
